ebook_metadata:
  title: ༄༅། །བློ་སྦྱོང་ཚིགས་རྐང་བརྒྱད་མ་ལོ་རྒྱུས་དང་བཅས་པ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། དགེ་བཤེས་འཆད་ཀ་བ།
  sku: IBA-MT-03-1
  layers:
  - book_title
  - author
  - quotation
web_metadata:
  title:
    en: A Commentary to the Eight Lines of Mind Training Supplemented with the Relevant
      Parables
    bo: བློ་སྦྱོང་ཚིག་རྐང་བརྒྱད་མ་ལོ་རྒྱུས་དང་བཅས་པ།
  collection:
    en: IBA Mind Training Series–  Book 3
    bo: རྒྱལ་ཡོངས་གསུང་རབ་བློ་སྦྱོང་བསྟར་རིམ།–  དེབ། ༣
  author:
    en: Geshe Chekawa
    bo: དགེ་བཤེས་འཆད་ཀ་བ།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-MT-03-1
  category:
    en: Mind Training
    bo: བློ་སྦྱོང།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-MT-03-1.epub
  description:
    en: This text is a commentary to theEight Lines of Mind Trainingsupplemented along
      with its relevant parable.
    bo: དགེ་བཤེས་འཆད་ཀ་བ་ཡེ་ཤེས་རྡོ་རྗེས་མཛད་པའི་བློ་སྦྱོང་ཚིག་རྐང་བརྒྱད་པའི་ལོས་རྒྱུས་དང་སྦྲགས་ནས་བཤད་པའི་འགྲེལ་པ།
